### ISSUE TITLE
Check the syntax of the generated feeds

### ISSUE THREAD

**Issue by alphadevx** [alphadevx/alpha#15]
Alpha supports the generation of RSS, RSS2, and Atom feeds from any DAO.  However according to this online validator, the syntax of none of these is correct:

http://feedvalidator.org/

We need to ensure that we are generating valid feeds.

**Comment by ubijco** [comment]
There are some simple ideas for how to validate the XML of the RSS and Atom feeds here:

https://stackoverflow.com/questions/12775921/how-to-check-if-a-url-is-a-valid-rss-feed-in-php

This seems to be the most straight-forward:

`$content = file_get_contents($this->feed); 
    try { $rss = new SimpleXmlElement($content); }
    catch(Exception $e){...}`

**Comment by alphadevx** [comment]
There are some simple ideas for how to validate the XML of the RSS and Atom feeds here:

https://stackoverflow.com/questions/12775921/how-to-check-if-a-url-is-a-valid-rss-feed-in-php

This seems to be the most straight-forward:

$content = file_get_contents($this->feed); try { $rss = new SimpleXmlElement($content); } catch(Exception $e){...}

**Comment by alphadevx** [comment]
This has already been done using the XMLReader->XML() method.
